test: run coverage tests to ensure broad case coverage

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -29,3 +29,11 @@ if [ $? -ne 0 ]; then
   echo "E2E tests failed, aborting commit."
   exit 1
 fi
+
+echo "Running Coverage tests..."
+npm run test:coverage
+if [ $? -ne 0 ]; then
+  echo "Coverage Failed, aborting commit."
+  exit 1
+fi
+
